GAMEPAD_BUTTON_LEFT=0
GAMEPAD_BUTTON_RIGHT=1
GAMEPAD_BUTTON_UP=2
GAMEPAD_BUTTON_DOWN=3
GAMEPAD_BUTTON_A=4
GAMEPAD_BUTTON_B=5
GAMEPAD_BUTTON_COUNT=6
GAMEPAD_PLAYER_1=0
GAMEPAD_PLAYER_2=1
GAMEPAD_PLAYER_3=2
GAMEPAD_PLAYER_4=3
GAMEPAD_PLAYER_5=4
GAMEPAD_PLAYER_6=5
GAMEPAD_PLAYER_7=6
GAMEPAD_PLAYER_8=7
GAMEPAD_PLAYER_COUNT=8
DIM GAMEPAD_BUTTON_STATE_OLD(GAMEPAD_PLAYER_COUNT,GAMEPAD_BUTTON_COUNT)
DIM GAMEPAD_BUTTON_STATE_NEW(GAMEPAD_PLAYER_COUNT,GAMEPAD_BUTTON_COUNT)
DIM GAMEPAD_BUTTON_PRESSED(GAMEPAD_PLAYER_COUNT,GAMEPAD_BUTTON_COUNT)
DIM GAMEPAD_BUTTON_RELEASED(GAMEPAD_PLAYER_COUNT,GAMEPAD_BUTTON_COUNT)
DEF GAMEPAD_UPDATE(I)
	FOR B=GAMEPAD_BUTTON_LEFT TO GAMEPAD_BUTTON_B
		O = GAMEPAD_BUTTON_STATE_NEW(I,B)
		N = BTN(I,B)
		GAMEPAD_BUTTON_STATE_OLD(I,B)=O
		GAMEPAD_BUTTON_STATE_OLD(I,B)=N
		GAMEPAD_BUTTON_PRESSED(I,B)=N AND NOT O
		GAMEPAD_BUTTON_RELEASED(I,B)=O AND NOT N
	NEXT B
ENDDEF