CLASS DIRECTION_T
    VAR next_direction=0
    VAR previous_direction=0
    VAR opposite_direction=0
    VAR delta_column=0
    VAR delta_row=0
    DEF INIT(n,p,o,dc,dr)
        ME.next_direction=n
        ME.previous_direction=p
        ME.opposite_direction=o
        ME.delta_column=dc
        ME.delta_row=dr
    ENDDEF
ENDCLASS
DIRECTION_NORTH=0
DIRECTION_EAST=1
DIRECTION_SOUTH=2
DIRECTION_WEST=3
DIRECTIONS = DICT()
temp = NEW(DIRECTION_T)
temp.INIT(DIRECTION_EAST,DIRECTION_SOUTH,DIRECTION_WEST,0,-1)
DIRECTIONS(DIRECTION_NORTH)=temp
temp = NEW(DIRECTION_T)
temp.INIT(DIRECTION_SOUTH,DIRECTION_WEST,DIRECTION_NORTH,1,0)
DIRECTIONS(DIRECTION_EAST)=temp
temp = NEW(DIRECTION_T)
temp.INIT(DIRECTION_WEST,DIRECTION_NORTH,DIRECTION_EAST,0,1)
DIRECTIONS(DIRECTION_SOUTH)=temp
temp = NEW(DIRECTION_T)
temp.INIT(DIRECTION_NORTH,DIRECTION_EAST,DIRECTION_SOUTH,-1,0)
DIRECTIONS(DIRECTION_WEST)=temp
