DEF DRAW_DISPLAY_MAP()
    DISPLAY_MAP = LOAD_RESOURCE("maze.map")
    FOR COLUMN=0 TO MAZE_COLUMNS-1
        FOR ROW=0 TO MAZE_ROWS-1
            TEMP=0
            FOR DIR=DIRECTION_FIRST TO DIRECTION_LAST
                IF MAZE_CELL_DOORS(COLUMN,ROW,DIR) THEN
                    TEMP=BOR(TEMP,SHL(1,DIR))
                ENDIF
            NEXT DIR
            MSET DISPLAY_MAP,1,COLUMN,ROW,TEMP
        NEXT ROW
    NEXT COLUMN
ENDDEF

