'UTILITY
IMPORT "keycodes.bas"
'RENDERABLES
IMPORT "displaymap.bas"
IMPORT "PASSAGEWAYS.BAS"
IMPORT "CHAMBERS.BAS"
IMPORT "CREATURESPRITES.BAS"
'DATA
IMPORT "directions.bas"
IMPORT "maze.bas"
IMPORT "ROOM.BAS"
IMPORT "PLAYER.BAS"
'STATES
IMPORT "INPLAY.BAS"
'MACHINE
IMPORT "STATEMACHINE.BAS"

DEF UPDATE(DELTA)
    IN_PLAY_DRAW_MAP()
    IN_PLAY_DRAW_PLAYER()
    IN_PLAY_MOVE_PLAYER()
ENDDEF

DEF RUN()
    DRV = DRIVER()
    GENERATE_MAZE()
    GENERATE_ROOMS()
    UPDATE_WITH(DRV, CALL(UPDATE))
ENDDEF

