IMPORT "directions.bas"
IMPORT "maze.bas"
IMPORT "keycodes.bas"
IMPORT "displaymap.bas"

GENERATE_MAZE()

ROOM_ROWS=15
ROOM_COLUMNS=15
ROOM_CELL_WIDTH = 8
ROOM_CELL_HEIGHT = 8

PASSAGEWAY_MAPS=LIST()
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY0.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY1.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY2.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY3.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY4.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY5.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY6.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY7.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY8.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY9.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY10.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY11.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY12.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY13.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY14.map"))
PUSH(PASSAGEWAY_MAPS,LOAD_RESOURCE("PASSAGEWAY15.map"))

SPRITE_DUDE=0
CREATURE_SPRITES = LIST()
PUSH(CREATURE_SPRITES, LOAD_RESOURCE("DUDE.sprite"))

ATLAS_COLUMN=0
ATLAS_ROW=0
ROOM_COLUMN=7
ROOM_ROW=7

DEF DRAW_MAP()
    TEMP=0
    FOR DIR=DIRECTION_FIRST TO DIRECTION_LAST
        IF MAZE_CELL_DOORS(ATLAS_COLUMN,ATLAS_ROW,DIR) THEN
            TEMP=BOR(TEMP,SHL(1,DIR))
        ENDIF
    NEXT DIR
    MAP PASSAGEWAY_MAPS(TEMP),0,0
ENDDEF

DEF DRAW_PLAYER()
    SPR CREATURE_SPRITES(SPRITE_DUDE),ROOM_COLUMN*ROOM_CELL_WIDTH,ROOM_ROW*ROOM_CELL_HEIGHT
ENDDEF

DEF MOVE_PLAYER()
    IF KEYP CODE_UP THEN
        IF ROOM_ROW>0 THEN 
            ROOM_ROW=ROOM_ROW-1
		ELSE
	        IF ATLAS_ROW>0 THEN 
	            ATLAS_ROW=ATLAS_ROW-1
				ROOM_ROW=ROOM_ROWS-1
	        ENDIF
		ENDIF
    ELSEIF KEYP CODE_DOWN THEN
        IF ROOM_ROW<ROOM_ROWS-1 THEN
            ROOM_ROW=ROOM_ROW+1
		ELSE
	        IF ATLAS_ROW<MAZE_ROWS-1 THEN
 	           ATLAS_ROW=ATLAS_ROW+1
				ROOM_ROW=0
  	        ENDIF
		ENDIF
    ELSEIF KEYP CODE_LEFT THEN
        IF ROOM_COLUMN>0 THEN 
            ROOM_COLUMN=ROOM_COLUMN-1
		ELSE
	        IF ATLAS_COLUMN>0 THEN
				ROOM_COLUMN=ROOM_COLUMNS-1
	            ATLAS_COLUMN=ATLAS_COLUMN-1
	        ENDIF
        ENDIF
    ELSEIF KEYP CODE_RIGHT THEN
        IF ROOM_COLUMN<ROOM_COLUMNS-1 THEN 
            ROOM_COLUMN=ROOM_COLUMN+1
        ELSE
        	IF ATLAS_COLUMN<MAZE_COLUMNS-1 THEN
				ROOM_COLUMN=0
         	    ATLAS_COLUMN=ATLAS_COLUMN+1
	        ENDIF
		ENDIF
    ENDIF
ENDDEF

DEF UPDATE(DELTA)
    DRAW_MAP()
    DRAW_PLAYER()
    MOVE_PLAYER()
ENDDEF

DEF RUN()
    DRV = DRIVER()
    UPDATE_WITH(DRV, CALL(UPDATE))
ENDDEF

