TILE_MAZE_0 = 0
TILE_MAZE_1 = 1
TILE_MAZE_2 = 2
TILE_MAZE_3 = 3
TILE_MAZE_4 = 4
TILE_MAZE_5 = 5
TILE_MAZE_6 = 6
TILE_MAZE_7 = 7
TILE_MAZE_8 = 8
TILE_MAZE_9 = 9
TILE_MAZE_10 = 10
TILE_MAZE_11 = 11
TILE_MAZE_12 = 12
TILE_MAZE_13 = 13
TILE_MAZE_14 = 14
TILE_MAZE_15 = 15
TILE_WALL_NORTH = 16
TILE_WALL_EAST = 17
TILE_WALL_SOUTH = 18
TILE_WALL_WEST = 19
TILE_CORNER_INSIDE_NORTHEAST=20
TILE_CORNER_INSIDE_SOUTHEAST=21
TILE_CORNER_INSIDE_SOUTHWEST=22
TILE_CORNER_INSIDE_NORTHWEST=23
TILE_CORNER_OUTSIDE_NORTHEAST=24
TILE_CORNER_OUTSIDE_SOUTHEAST=25
TILE_CORNER_OUTSIDE_SOUTHWEST=26
TILE_CORNER_OUTSIDE_NORTHWEST=27
TILE_DOOR_NORTH=28
TILE_DOOR_EAST=29
TILE_DOOR_SOUTH=30
TILE_DOOR_WEST=31
TILE_SOLID=32
TILE_FLOOR=33

DEF CAN_WALK_ON_TILE(T)
    IF T=TILE_FLOOR THEN
        RETURN TRUE
    ENDIF
    RETURN FALSE
ENDDEF
